package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"database/sql"
	"strconv"
)

// Department represents a row from 'public.departments'.
type Department struct {
	DeptID    int64            `json:"departmentid"`     // id
	DepartmentName sql.NullString `json:"departmentname"` // d_name
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [Department] exists in the database.
func (d *Department) Exists() bool {
	return d._exists
}

// Deleted returns true when the [Department] has been marked for deletion
// from the database.
func (d *Department) Deleted() bool {
	return d._deleted
}

// Insert inserts the [Department] to the database.
func (d *Department) Insert(ctx context.Context, db DB) error {
	switch {
	case d._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case d._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (primary key generated and returned by database)
	const sqlstr = `INSERT INTO public.departments (` +
		`d_name` +
		`) VALUES (` +
		`$1` +
		`) RETURNING id`
	// run
	logf(sqlstr, d.DepartmentName)
	if err := db.QueryRowContext(ctx, sqlstr, d.DepartmentName).Scan(&d.DeptID); err != nil {
		return logerror(err)
	}
	// set exists
	d._exists = true
	return nil
}

// Update updates a [Department] in the database.
func (d *Department) Update(ctx context.Context, db DB) error {
	switch {
	case !d._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case d._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with composite primary key
	const sqlstr = `UPDATE public.departments SET ` +
		`d_name = $1 ` +
		`WHERE id = $2`
	// run
	logf(sqlstr, d.DepartmentName, d.DeptID)
	if _, err := db.ExecContext(ctx, sqlstr, d.DepartmentName, d.DeptID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [Department] to the database.
func (d *Department) Save(ctx context.Context, db DB) error {
	if d.Exists() {
		return d.Update(ctx, db)
	}
	return d.Insert(ctx, db)
}

// Upsert performs an upsert for [Department].
func (d *Department) Upsert(ctx context.Context, db DB) error {
	switch {
	case d._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO public.departments (` +
		`id, d_name` +
		`) VALUES (` +
		`$1, $2` +
		`)` +
		` ON CONFLICT (id) DO ` +
		`UPDATE SET ` +
		`d_name = EXCLUDED.d_name `
	// run
	logf(sqlstr, d.DeptID, d.DepartmentName)
	if _, err := db.ExecContext(ctx, sqlstr, d.DeptID, d.DepartmentName); err != nil {
		return logerror(err)
	}
	// set exists
	d._exists = true
	return nil
}

// Delete deletes the [Department] from the database.
func (d *Department) Delete(ctx context.Context, db DB) error {
	switch {
	case !d._exists: // doesn't exist
		return nil
	case d._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM public.departments ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, d.DeptID)
	if _, err := db.ExecContext(ctx, sqlstr, d.DeptID); err != nil {
		return logerror(err)
	}
	// set deleted
	d._deleted = true
	return nil
}

// DepartmentByID retrieves a row from 'public.departments' as a [Department].
//
// Generated from index 'departments_pkey'.
func DepartmentByID(ctx context.Context, db DB, id int) (*Department, error) {
	// query
	const sqlstr = `SELECT ` +
		`id, d_name ` +
		`FROM public.departments ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, id)
	d := Department{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, id).Scan(&d.DeptID, &d.DepartmentName); err != nil {
		return nil, logerror(err)
	}
	return &d, nil
}

func Departments(ctx context.Context, db DB, flt string, start int, cnt int) ([]*Department, error) {
	var sqlstr, whereString string

	whereString = ""
	if flt!= "" {
        whereString = "WHERE " + flt
    }

	lmt := ""
	if cnt > 0 {
		lmt = " LIMIT " + strconv.Itoa(start)  + " " + strconv.Itoa(cnt) 
	} 

	sqlstr = `SELECT ` +
				`id, d_name ` +
				`FROM public.departments ` + whereString + lmt
	
	rows, err := db.QueryContext(ctx,sqlstr)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	departments := []*Department{}

	for rows.Next() {
		t := &Department{}
		err = rows.Scan(
			&t.DeptID, 
			&t.DepartmentName,
		)

		if err != nil {
		return nil, err
		}

		departments = append(departments, t)
	}

	if err = rows.Err(); err != nil {
		return nil, err
	}

	return departments, nil
	
}
