package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"database/sql"
	"fmt"
	"log"
	"strconv"
	"strings"
)

// Employee represents a row from 'clinician_app.employees'.
type Employee struct {
	EmpID             int            `json:"employeeid"` // id
	Fname             sql.NullString `json:"firstname"`  // fname
	Lname             sql.NullString `json:"lastname"`   // lname
	Oname             sql.NullString `json:"othername"`  // oname
	EmpTitleID        sql.NullInt64  `json:"emptitle_id"`
	EmpTitle          sql.NullString `json:"employeetitle"`   // title
	Specialisation    sql.NullString `json:"specialisation"`  // specialisation
	EmpDepartment     int64          `json:"department_id"`   // department id
	EmpDepartmentName sql.NullString `json:"department_name"` // department
	EmpFacility       int64          `json:"facility_id"`     // facility id
	EmpFacilityName   sql.NullString `json:"facility_name"`   // facility name
	CreatedBy         sql.NullInt64  `json:"createdby_id"`    // created_by
	CreatedOn         sql.NullTime   `json:"createdon_date"`  // created_on
	LeaveStatus       sql.NullString `json:"leave_status"`    // leave_status
	ReturnDate        sql.NullTime   `json:"return_date"`     // return_on
	// xo fields
	_exists, _deleted bool
}

// History represents an employee's leave record
type LeaveHistory struct {
	ID             int
	EmpID          sql.NullInt64
	LeaveTypeName  sql.NullString
	LeaveTypeID    sql.NullInt64
	StartDate      sql.NullTime
	EndDate        sql.NullTime
	LeaveStatus    sql.NullString
	Comments       sql.NullString
	SubmittedBy    sql.NullInt64
	SubmissionDate sql.NullTime
	ReviewedOn     sql.NullTime
	// xo fields
	_exists, _deleted bool
}

type FacilityLeaveReviewRow struct {
	ID             int
	EmpID          int64
	EmployeeName   string
	DepartmentName string
	LeaveTypeName  string
	StartDate      sql.NullTime
	EndDate        sql.NullTime
	LeaveStatus    sql.NullString
	Comments       sql.NullString
	SubmissionDate sql.NullTime
	ReviewedOn     sql.NullTime
	ApprovedByName sql.NullString
	Actionable     bool
}

type FacilityLeaveReviewSummary struct {
	PendingLeaves  int
	ApprovedLeaves int
	DeclinedLeaves int
}

// DashboardData holds the data for the cards
type DashboardData struct {
	FacilitiesCount int
	TotalStaff      int
	StaffPresent    int
	StaffOnLeave    int
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the [Employee] exists in the database.
func (e *Employee) Exists() bool {
	return e._exists
}

// Deleted returns true when the [Employee] has been marked for deletion
// from the database.
func (e *Employee) Deleted() bool {
	return e._deleted
}

// Insert inserts the Employee into the database (from provided code)
func (e *Employee) Insert(ctx context.Context, db DB) error {
	switch {
	case e._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case e._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}

	// Query the last id value in the weeklyreport table
	var lastID int
	lastIDQuery := `SELECT COALESCE(MAX(id), 0) FROM clinician_app.employees`
	if err := db.QueryRowContext(ctx, lastIDQuery).Scan(&lastID); err != nil {
		return logerror(err)
	}

	// Calculate new ID starting from lastID + 1
	newID := lastID + 1

	// insert (primary key generated and returned by database)
	const sqlstr = `INSERT INTO clinician_app.employees (` +
		`id, fname, lname, oname, title, specialisation, department, facility, created_by, created_on` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8, $9, $10` +
		`) RETURNING id`
	// run
	logf(sqlstr, newID, e.Fname, e.Lname, e.Oname, e.EmpTitleID, e.Specialisation, e.EmpDepartment, e.EmpFacility, e.CreatedBy, e.CreatedOn)
	if err := db.QueryRowContext(ctx, sqlstr, newID, e.Fname, e.Lname, e.Oname, e.EmpTitleID, e.Specialisation, e.EmpDepartment, e.EmpFacility, e.CreatedBy, e.CreatedOn).Scan(&e.EmpID); err != nil {
		return logerror(err)
	}
	// set exists
	e._exists = true
	return nil
}

// Fxn to insert to [staffleave] table (from provided code)
func (e *LeaveHistory) InsertLeave(ctx context.Context, db DB) error {

	log.Printf("InsertLeave executed:")

	switch {
	case e._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case e._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}

	// Query the last id value in the weeklyreport table
	var lastID int
	lastIDQuery := `SELECT COALESCE(MAX(leave_id), 0) FROM clinician_app.staffleave`
	if err := db.QueryRowContext(ctx, lastIDQuery).Scan(&lastID); err != nil {
		return logerror(err)
	}

	// Calculate new ID starting from lastID + 1
	newID := lastID + 1
	log.Printf("New leave_id: %+d", newID)

	// insert (primary key generated and returned by database)
	const sqlstr = `INSERT INTO clinician_app.staffleave (` +
		`leave_id, employee_id, start_date, end_date, leave_status, approved_by, created_on, leave_type_id, notes` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8, $9` +
		`) RETURNING leave_id`
	// run
	logf(sqlstr, newID, e.EmpID, e.StartDate, e.EndDate, e.LeaveStatus, e.SubmittedBy, e.SubmissionDate, e.LeaveTypeID, e.Comments)
	if err := db.QueryRowContext(ctx, sqlstr, newID, e.EmpID, e.StartDate, e.EndDate, e.LeaveStatus, e.SubmittedBy, e.SubmissionDate, e.LeaveTypeID, e.Comments).Scan(&e.ID); err != nil {
		return logerror(err)
	}
	// set exists
	e._exists = true
	return nil
}

// Update updates a [Employee] in the database.
func (e *Employee) Update(ctx context.Context, db DB) error {
	switch {
	case !e._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case e._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with composite primary key
	const sqlstr = `UPDATE clinician_app.employees SET ` +
		`fname = $1, lname = $2, oname = $3, title = $4, specialisation = $5, department = $6, facility = $7, created_by = $8, created_on = $9 ` +
		`WHERE id = $10`
	// run
	logf(sqlstr, e.Fname, e.Lname, e.Oname, e.EmpTitleID, e.Specialisation, e.EmpDepartment, e.EmpFacility, e.CreatedBy, e.CreatedOn, e.EmpID)
	if _, err := db.ExecContext(ctx, sqlstr, e.Fname, e.Lname, e.Oname, e.EmpTitleID, e.Specialisation, e.EmpDepartment, e.EmpFacility, e.CreatedBy, e.CreatedOn, e.EmpID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the [Employee] to the database.
func (e *Employee) Save(ctx context.Context, db DB) error {
	if e.Exists() {
		return e.Update(ctx, db)
	}
	return e.Insert(ctx, db)
}

// UpdatePendingLeave updates a pending leave request owned by the employee.
func (e *LeaveHistory) UpdatePendingLeave(ctx context.Context, db DB) (bool, error) {
	const sqlstr = `UPDATE clinician_app.staffleave SET ` +
		`start_date = $1, end_date = $2, leave_type_id = $3, notes = $4 ` +
		`WHERE leave_id = $5 AND employee_id = $6 AND leave_status = 'Pending'`

	result, err := db.ExecContext(ctx, sqlstr, e.StartDate, e.EndDate, e.LeaveTypeID, e.Comments, e.ID, e.EmpID)
	if err != nil {
		return false, logerror(err)
	}

	rowsAffected, err := result.RowsAffected()
	if err != nil {
		return false, logerror(err)
	}

	return rowsAffected > 0, nil
}

// DeletePendingLeave deletes a pending leave request owned by the employee.
func DeletePendingLeave(ctx context.Context, db DB, leaveID int, employeeID int64) (bool, error) {
	const sqlstr = `DELETE FROM clinician_app.staffleave ` +
		`WHERE leave_id = $1 AND employee_id = $2 AND leave_status = 'Pending'`

	result, err := db.ExecContext(ctx, sqlstr, leaveID, employeeID)
	if err != nil {
		return false, logerror(err)
	}

	rowsAffected, err := result.RowsAffected()
	if err != nil {
		return false, logerror(err)
	}

	return rowsAffected > 0, nil
}

// Upsert performs an upsert for [Employee].
func (e *Employee) Upsert(ctx context.Context, db DB) error {
	switch {
	case e._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO clinician_app.employees (` +
		`id, fname, lname, oname, title, specialisation, department, facility, created_by, created_on` +
		`) VALUES (` +
		`$1, $2, $3, $4, $5, $6, $7, $8, $9, $10` +
		`)` +
		` ON CONFLICT (id) DO ` +
		`UPDATE SET ` +
		`fname = EXCLUDED.fname, lname = EXCLUDED.lname, oname = EXCLUDED.oname, title = EXCLUDED.title, specialisation = EXCLUDED.specialisation, department = EXCLUDED.department, facility = EXCLUDED.facility, created_by = EXCLUDED.created_by, created_on = EXCLUDED.created_on `
	// run
	logf(sqlstr, e.EmpID, e.Fname, e.Lname, e.Oname, e.EmpTitle, e.Specialisation, e.EmpDepartment, e.EmpFacility, e.CreatedBy, e.CreatedOn)
	if _, err := db.ExecContext(ctx, sqlstr, e.EmpID, e.Fname, e.Lname, e.Oname, e.EmpTitle, e.Specialisation, e.EmpDepartment, e.EmpFacility, e.CreatedBy, e.CreatedOn); err != nil {
		return logerror(err)
	}
	// set exists
	e._exists = true
	return nil
}

// Delete deletes the [Employee] from the database.
func (e *Employee) Delete(ctx context.Context, db DB) error {
	switch {
	case !e._exists: // doesn't exist
		return nil
	case e._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM clinician_app.employees ` +
		`WHERE id = $1`
	// run
	logf(sqlstr, e.EmpID)
	if _, err := db.ExecContext(ctx, sqlstr, e.EmpID); err != nil {
		return logerror(err)
	}
	// set deleted
	e._deleted = true
	return nil
}

// EmployeeByID retrieves a row from 'clinician_app.employees' as a [Employee].
//
// Generated from index 'employees_pkey'.
func EmployeeByID(ctx context.Context, db DB, id int) (*Employee, error) {
	// query
	const sqlstr = `SELECT ` +
		`e.id, e.fname, e.lname, e.oname, e.title, st.title, e.specialisation, e.department, e.facility, e.created_by, e.created_on ` +
		`FROM clinician_app.employees e ` +
		`LEFT JOIN clinician_app.specialist_titles st ON e.title = st.id ` +
		`WHERE e.id = $1`
	// run
	logf(sqlstr, id)
	e := Employee{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, id).Scan(&e.EmpID, &e.Fname, &e.Lname, &e.Oname, &e.EmpTitleID, &e.EmpTitle, &e.Specialisation, &e.EmpDepartment, &e.EmpFacility, &e.CreatedBy, &e.CreatedOn); err != nil {
		return nil, logerror(err)
	}
	return &e, nil
}

// Fxn Employee with hospitalID, leave, department, search and limit parameters
func Employees(ctx context.Context, db *sql.DB, facilityID int64, leave string, departmentID int64, search string, limit int) ([]*Employee, error) {
	var sqlstr string
	whereClauses := []string{}
	args := []interface{}{}
	argIndex := 1

	if facilityID > 0 {
		whereClauses = append(whereClauses, fmt.Sprintf("e.facility = $%d", argIndex))
		args = append(args, facilityID)
		argIndex++
	}

	if departmentID > 0 {
		whereClauses = append(whereClauses, fmt.Sprintf("e.department = $%d", argIndex))
		args = append(args, departmentID)
		argIndex++
	}

	if search = strings.TrimSpace(search); search != "" {
		if id, err := strconv.Atoi(search); err == nil {
			whereClauses = append(whereClauses, fmt.Sprintf("(e.id = $%d OR LOWER(CONCAT(COALESCE(e.fname, ''), ' ', COALESCE(e.lname, ''), ' ', COALESCE(e.oname, ''))) LIKE LOWER($%d))", argIndex, argIndex+1))
			args = append(args, id, "%"+strings.ToLower(search)+"%")
			argIndex += 2
		} else {
			whereClauses = append(whereClauses, fmt.Sprintf("LOWER(CONCAT(COALESCE(e.fname, ''), ' ', COALESCE(e.lname, ''), ' ', COALESCE(e.oname, ''))) LIKE LOWER($%d)", argIndex))
			args = append(args, "%"+strings.ToLower(search)+"%")
			argIndex++
		}
	}

	if leave != "" {
		switch leave {
		case "Valid", "on_leave":
			whereClauses = append(whereClauses, "sl.leave_status IS NOT NULL")
		case "on_duty":
			whereClauses = append(whereClauses, "sl.leave_status IS NULL")
		default:
			whereClauses = append(whereClauses, fmt.Sprintf("sl.leave_status = '%s'", leave))
		}
	}

	whereString := ""
	if len(whereClauses) > 0 {
		whereString = " WHERE " + strings.Join(whereClauses, " AND ")
	}

	sqlstr = `SELECT
			e.id,
			e.fname,
			e.lname,
			e.oname,
			st.title,
			e.specialisation,
			d.d_name,
			f.f_name,
			e.created_by,
			e.created_on,
			CASE WHEN sl.leave_status IS NOT NULL THEN 'On Leave' ELSE NULL END AS leave_status,
			COALESCE(sl.return_date, sl.end_date) AS return_date
                FROM clinician_app.employees e
                LEFT JOIN clinician_app.facilities f ON e.facility = f.id
			LEFT JOIN clinician_app.specialist_titles st ON e.title = st.id
                LEFT JOIN clinician_app.departments d ON e.department = d.id
			LEFT JOIN LATERAL (
				SELECT
					sl.leave_status,
					sl.return_date,
					sl.end_date
				FROM clinician_app.staffleave sl
				WHERE sl.employee_id = e.id
					AND COALESCE(sl.leave_status, '') IN ('Valid', 'Approved')
					AND sl.start_date::date <= CURRENT_DATE
					AND sl.end_date::date >= CURRENT_DATE
				ORDER BY sl.end_date DESC, sl.leave_id DESC
				LIMIT 1
			) sl ON TRUE` +
		whereString +
		` ORDER BY e.id`

	if limit > 0 {
		sqlstr += fmt.Sprintf(" LIMIT %d", limit)
	}

	rows, err := db.QueryContext(ctx, sqlstr, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	employees := []*Employee{}

	for rows.Next() {
		e := &Employee{}
		err = rows.Scan(
			&e.EmpID,
			&e.Fname,
			&e.Lname,
			&e.Oname,
			&e.EmpTitle,
			&e.Specialisation,
			&e.EmpDepartmentName,
			&e.EmpFacilityName,
			&e.CreatedBy,
			&e.CreatedOn,
			&e.LeaveStatus,
			&e.ReturnDate,
		)

		if err != nil {
			return nil, err
		}

		employees = append(employees, e)
	}

	if err = rows.Err(); err != nil {
		return nil, err
	}

	return employees, nil
}

// GetFacilitiesAndDepartments retrieves facilities and departments from the database.
func GetFacilitiesAndDepartments(db *sql.DB) ([]*Facility, []*Department, error) {
	facilities := []*Facility{}
	departments := []*Department{}

	// Fetch facilities
	facilityRows, err := db.Query("SELECT id, f_name, f_level, f_lg, created_by, created_on FROM clinician_app.facilities")
	if err != nil {
		return nil, nil, err
	}
	defer facilityRows.Close()

	for facilityRows.Next() {
		facility := &Facility{}
		if err := facilityRows.Scan(
			&facility.FacilityID,
			&facility.FacilityName,
			&facility.FacilityLevel,
			&facility.FacilityLg,
			&facility.FacilityCreatedBy,
			&facility.FacilityCreatedOn,
		); err != nil {
			return nil, nil, err
		}
		facilities = append(facilities, facility)
	}

	// Fetch departments
	departmentRows, err := db.Query("SELECT id, d_name FROM clinician_app.departments")
	if err != nil {
		return nil, nil, err
	}
	defer departmentRows.Close()

	for departmentRows.Next() {
		department := &Department{}
		if err := departmentRows.Scan(
			&department.DeptID,
			&department.DepartmentName,
		); err != nil {
			return nil, nil, err
		}
		departments = append(departments, department)
	}

	return facilities, departments, nil
}

// GetHistory() fxn to retrieve user leave request history from the db
func GetHistory(db *sql.DB, employeeID int) ([]*LeaveHistory, error) {
	query := `
	SELECT a.leave_id, a.employee_id, l.leave_type_name, a.leave_type_id, a.start_date, a.end_date, a.leave_status, a.notes, a.created_on, a.reviewed_on
        FROM clinician_app.staffleave a
        JOIN clinician_app.leavetypes l ON a.leave_type_id = l.leave_type_id
        WHERE a.employee_id = $1
        ORDER BY a.created_on DESC, a.leave_id DESC
    `

	rows, err := db.Query(query, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	history := []*LeaveHistory{}
	for rows.Next() {
		h := &LeaveHistory{}
		err = rows.Scan(&h.ID, &h.EmpID, &h.LeaveTypeName, &h.LeaveTypeID, &h.StartDate, &h.EndDate, &h.LeaveStatus, &h.Comments, &h.SubmissionDate, &h.ReviewedOn)
		if err != nil {
			return nil, err
		}
		history = append(history, h)
	}

	if err = rows.Err(); err != nil {
		return nil, err
	}

	return history, nil
}

// PendingLeaveByID returns a pending leave request owned by the specified employee.
func PendingLeaveByID(ctx context.Context, db DB, leaveID int, employeeID int64) (*LeaveHistory, error) {
	const sqlstr = `SELECT ` +
		`a.leave_id, a.employee_id, l.leave_type_name, a.leave_type_id, a.start_date, a.end_date, a.leave_status, a.notes, a.created_on ` +
		`FROM clinician_app.staffleave a ` +
		`JOIN clinician_app.leavetypes l ON a.leave_type_id = l.leave_type_id ` +
		`WHERE a.leave_id = $1 AND a.employee_id = $2 AND a.leave_status = 'Pending'`

	leave := &LeaveHistory{_exists: true}
	err := db.QueryRowContext(ctx, sqlstr, leaveID, employeeID).Scan(
		&leave.ID,
		&leave.EmpID,
		&leave.LeaveTypeName,
		&leave.LeaveTypeID,
		&leave.StartDate,
		&leave.EndDate,
		&leave.LeaveStatus,
		&leave.Comments,
		&leave.SubmissionDate,
	)
	if err != nil {
		return nil, logerror(err)
	}

	return leave, nil
}

func GetFacilityLeaveReview(ctx context.Context, db DB, facilityID int64, filterStatus string) ([]*FacilityLeaveReviewRow, error) {
	// Draft leave requests (empty or explicit Draft status) are visible only in the creator's own history.
	whereClause := `WHERE e.facility = $1 AND COALESCE(a.leave_status, '') NOT IN ('', 'Draft')`
	args := []interface{}{facilityID}

	switch filterStatus {
	case "pending":
		whereClause += ` AND COALESCE(a.leave_status, '') = 'Pending'`
	case "approved":
		whereClause += ` AND COALESCE(a.leave_status, '') IN ('Approved', 'Valid')`
	case "declined":
		whereClause += ` AND COALESCE(a.leave_status, '') IN ('Rejected', 'Declined')`
	case "expired":
		whereClause += ` AND COALESCE(a.leave_status, '') = 'Expired'`
	case "on_leave":
		whereClause += ` AND COALESCE(a.leave_status, '') IN ('Approved', 'Valid') AND a.start_date::date <= CURRENT_DATE AND a.end_date::date >= CURRENT_DATE`
	default:
		filterStatus = "all"
	}

	sqlstr := `
		SELECT
			a.leave_id,
			e.id,
			TRIM(CONCAT(COALESCE(e.fname, ''), ' ', COALESCE(e.lname, ''))) AS employee_name,
			COALESCE(d.d_name, '') AS department_name,
			COALESCE(l.leave_type_name, '') AS leave_type_name,
			a.start_date,
			a.end_date,
			a.leave_status,
			a.notes,
			a.created_on,
			a.reviewed_on,
			NULLIF(TRIM(CONCAT(COALESCE(ap.fname, ''), ' ', COALESCE(ap.lname, ''))), '') AS approved_by_name
		FROM clinician_app.staffleave a
		JOIN clinician_app.employees e ON e.id = a.employee_id
		LEFT JOIN clinician_app.departments d ON d.id = e.department
		LEFT JOIN clinician_app.leavetypes l ON l.leave_type_id = a.leave_type_id
		LEFT JOIN clinician_app.employees ap ON ap.id = a.approved_by
		` + whereClause + `
		ORDER BY a.created_on DESC, a.leave_id DESC
	`

	rows, err := db.QueryContext(ctx, sqlstr, args...)
	if err != nil {
		return nil, logerror(err)
	}
	defer rows.Close()

	items := []*FacilityLeaveReviewRow{}
	for rows.Next() {
		item := &FacilityLeaveReviewRow{}
		if err := rows.Scan(
			&item.ID,
			&item.EmpID,
			&item.EmployeeName,
			&item.DepartmentName,
			&item.LeaveTypeName,
			&item.StartDate,
			&item.EndDate,
			&item.LeaveStatus,
			&item.Comments,
			&item.SubmissionDate,
			&item.ReviewedOn,
			&item.ApprovedByName,
		); err != nil {
			return nil, logerror(err)
		}

		item.Actionable = item.LeaveStatus.Valid && item.LeaveStatus.String == "Pending"
		items = append(items, item)
	}

	if err := rows.Err(); err != nil {
		return nil, logerror(err)
	}

	return items, nil
}

func ApproveFacilityLeave(ctx context.Context, db DB, leaveID int, facilityID int64, approverID int64) (bool, error) {
	const sqlstr = `
		UPDATE clinician_app.staffleave a
		SET leave_status = 'Approved', approved_by = $3, reviewed_on = NOW()
		FROM clinician_app.employees e
		WHERE a.leave_id = $1
			AND e.id = a.employee_id
			AND e.facility = $2
			AND COALESCE(a.leave_status, '') = 'Pending'
	`

	result, err := db.ExecContext(ctx, sqlstr, leaveID, facilityID, approverID)
	if err != nil {
		return false, logerror(err)
	}

	rowsAffected, err := result.RowsAffected()
	if err != nil {
		return false, logerror(err)
	}

	return rowsAffected > 0, nil
}

func DeclineFacilityLeave(ctx context.Context, db DB, leaveID int, facilityID int64, approverID int64) (bool, error) {
	const sqlstr = `
		UPDATE clinician_app.staffleave a
		SET leave_status = 'Rejected', approved_by = $3, reviewed_on = NOW()
		FROM clinician_app.employees e
		WHERE a.leave_id = $1
			AND e.id = a.employee_id
			AND e.facility = $2
			AND COALESCE(a.leave_status, '') = 'Pending'
	`

	result, err := db.ExecContext(ctx, sqlstr, leaveID, facilityID, approverID)
	if err != nil {
		return false, logerror(err)
	}

	rowsAffected, err := result.RowsAffected()
	if err != nil {
		return false, logerror(err)
	}

	return rowsAffected > 0, nil
}

func GetFacilityLeaveReviewSummary(ctx context.Context, db DB, facilityID int64) (FacilityLeaveReviewSummary, error) {
	var summary FacilityLeaveReviewSummary

	const sqlstr = `
		SELECT
			COUNT(*) FILTER (
				WHERE COALESCE(a.leave_status, '') = 'Pending'
			) AS pending_leaves,
			COUNT(*) FILTER (
				WHERE COALESCE(a.leave_status, '') IN ('Approved', 'Valid')
			) AS approved_leaves,
			COUNT(*) FILTER (
				WHERE COALESCE(a.leave_status, '') IN ('Rejected', 'Declined')
			) AS declined_leaves
		FROM clinician_app.staffleave a
		JOIN clinician_app.employees e ON e.id = a.employee_id
		WHERE e.facility = $1
	`

	err := db.QueryRowContext(ctx, sqlstr, facilityID).Scan(
		&summary.PendingLeaves,
		&summary.ApprovedLeaves,
		&summary.DeclinedLeaves,
	)

	return summary, err
}

// Query the db for dashboard card data
func GetDashboardData(db *sql.DB, facilityID int) (DashboardData, error) {
	var data DashboardData
	var facilityCount int
	var staffOnLeave int
	var totalStaff int

	// Query to count total staff filtered by facilityID
	queryFacilities := `
		SELECT COUNT(*)
		FROM clinician_app.facilities
	`
	err := db.QueryRow(queryFacilities).Scan(&facilityCount)
	if err != nil {
		return data, err
	}

	// Query to count staff on leave (leave_status = 'Valid') filtered by facilityID
	queryLeave := `
		SELECT COUNT(*)
		FROM clinician_app.staffleave_view s
		INNER JOIN clinician_app.employees e ON s.employee_id = e.id
		WHERE e.facility = $1 AND s.leave_status IN ('Valid', 'Approved')
	`
	err = db.QueryRow(queryLeave, facilityID).Scan(&staffOnLeave)
	if err != nil {
		return data, err
	}

	// Query to count total staff filtered by facilityID
	queryTotal := `
		SELECT COUNT(*)
		FROM clinician_app.employees e
		WHERE e.facility = $1
	`
	err = db.QueryRow(queryTotal, facilityID).Scan(&totalStaff)
	if err != nil {
		return data, err
	}

	// Calculate staff present
	staffPresent := totalStaff - staffOnLeave

	// Assign values to DashboardData struct
	data.FacilitiesCount = facilityCount
	data.TotalStaff = totalStaff
	data.StaffOnLeave = staffOnLeave
	data.StaffPresent = staffPresent

	return data, nil
}
